FROM python:3.11-slim
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    google-chrome-stable \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

RUN useradd -m roberto_user
USER roberto_user

HEALTHCHECK --interval=30s --timeout=5s \
  CMD ls consulta_onpe.py || exit 1

CMD ["python", "consulta_onpe.py"]