FROM ghcr.io/puppeteer/puppeteer:24.7.2
WORKDIR /app
COPY package.json ./
RUN npm install --omit=dev
COPY . .
USER pptruser
EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=5s CMD node -e "fetch('http://localhost:3000').then(()=>process.exit(0)).catch(()=>process.exit(1))"
CMD ["npm","start"]